version: '3'
volumes:
  socket-volume:
services:
  postgres_local:
    build:
      context: postgres
    volumes:
      - socket-volume:/var/run
    environment:
      POSTGRES_PASSWORD: 'envizon'
      POSTGRES_USER: 'envizon'
      POSTGRES_DB: 'envizon'
      POSTGRES_DEVELOPMENT_DB: 'envizon_development'
      POSTGRES_TEST_DB: 'envizon_test'
  envizon_local:
    build:
      context: ..
      dockerfile: docker/Dockerfile_local
    depends_on:
      - postgres_local
    network_mode: 'host'
    ports:
      - 3000:3000
    volumes:
      - ../:/usr/src/app/envizon
      - socket-volume:/var/run
    environment:
      POSTGRES_PASSWORD: 'envizon'
      POSTGRES_USER: 'envizon'
      POSTGRES_DB: 'envizon'
      POSTGRES_HOST: '/var/run/postgresql'
      SECRET_KEY_BASE:
      RAILS_ENV: 'production'
      RAILS_FORCE_SSL: 'true'
      RAILS_SERVE_STATIC_FILES: 'true'
      SSL_KEY_PATH:
      SSL_CERT_PATH:
    entrypoint: /entrypoint_local.sh
  selenium:
    image: selenium/standalone-chrome
    expose: 
      - "4444"
    volumes: 
      - /dev/shm:/dev/shm

