version: '3'
volumes:
  socket-volume:
services:
  postgres:
    image: postgres:alpine
    volumes:
      - socket-volume:/var/run
    environment:
      POSTGRES_PASSWORD: 'envizon'
      POSTGRES_USER: 'envizon'
      POSTGRES_DB: 'envizon'
  envizon:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    network_mode: 'host'
    ports:
      - 3000:3000
    volumes:
      - socket-volume:/var/run
    environment:
      POSTGRES_PASSWORD: 'envizon'
      POSTGRES_USER: 'envizon'
      POSTGRES_DB: 'envizon'
      POSTGRES_HOST: '/var/run/postgresql'
      RAILS_ENV: 'production'
      RAILS_FORCE_SSL: 'true'
      RAILS_SERVE_STATIC_FILES: 'true'
      SECRET_KEY_BASE:
      SSL_KEY_PATH:
      SSL_CERT_PATH:
        entrypoint: /entrypoint.sh
